export enum CosStorageClass {
    STANDARD = 'STANDARD',
    STANDARD_IA = 'STANDARD_IA',
    ARCHIVE = 'ARCHIVE',
    DEEP_ARCHIVE = 'DEEP_ARCHIVE',
    INTELLIGENT_TIERING = 'INTELLIGENT_TIERING',
    MAZ_STANDARD = 'MAZ_STANDARD',
    MAZ_STANDARD_IA = 'MAZ_STANDARD_IA',
    MAZ_INTELLIGENT_TIERING = 'MAZ_INTELLIGENT_TIERING',
}
